<?xml version="1.0"?>
<package format="2">
  <name>acados_vendor</name>
  <version>0.1.0</version>
  <description>ROS1 Noetic vendor package for the acados solver stack.</description>

  <maintainer email="867768510@qq.com">Lxk_buaa</maintainer>
  <author email="867768510@qq.com">Lxk_buaa</author>
  <license>BSD-2-Clause</license>

  <buildtool_depend>catkin</buildtool_depend>

  <test_depend>rostest</test_depend>

  <export>
  </export>
</package>
